name: setup
description: Sets up the build environment

inputs:
  sln:
    default: src/Riganti.Selenium.sln
    description: Path to a Visual Studio solution
    required: false

runs:
  using: composite
  steps:

  # nuget
  - uses: nuget/setup-nuget@v2
    with:
      nuget-version: '6.x'
  - uses: actions/cache@v4
    id: nuget-cache
    with:
      path: ~/.nuget/packages
      key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
      restore-keys: ${{ runner.os }}-nuget-

  # .NET
  - uses: actions/setup-dotnet@v4
    with:
      dotnet-version: |
        7.0.x
        6.0.x
        5.0.x
        3.1.x
  - if: ${{ runner.os == 'Windows' }}
    uses: microsoft/setup-msbuild@v1.1

  # restore nuget packages
  - if: ${{ runner.os == 'Windows' }}
    run: msbuild ${{ inputs.sln }} -t:Restore
    shell: pwsh
  - if: ${{ runner.os != 'Windows' }}
    run: dotnet restore ${{ inputs.sln }}
    shell: bash
