name: Run tests

on:
  push:
    branches:
      - "main"
      - "release/**"
  pull_request:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  ui-tests:
    name: UI tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 50
    strategy:
      fail-fast: false # don't kill tests when one environment fails
      matrix:
        # specify only one config, all other configurations are included explicitly
        browser: [firefox, chrome]
        os: [ubuntu-latest]

    env:
      SLN: "src/Riganti.Selenium.WithoutCoordinator.sln"
    steps:
      - uses: actions/checkout@v4
      - name: Set up
        uses: ./.github/setup
        with:
          sln: ${{ env.SLN }}
      - run: type firefox
      - run: type geckodriver
      - name: Run UI tests
        uses: ./.github/uitest
        with:
          browser: ${{ matrix.browser }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-configuration: "${{ matrix.environment == 'Production' && 'Release' || 'Debug' }}"
          runtime-environment: "${{ matrix.environment }}"
